g_fps = 20
g_source = 0
g_calibration_preview_window = "Camera Calibration Preview Window"
g_calibration_progress_window = "Camera Calibration Progress Window"
g_tracker_live_window = "Live Aruco Tracker"
g_minimum_calib_images = 20
g_calib_images_folder = "calib_images"
g_calib_data_folder = "calib_data"
g_calib_data_file_name = "camera_calibration.yaml"
g_marker_length_in_meters = 0.1